; PlatformIO — Motor Bridge + OLED Display

[platformio]
src_dir = sketch_pi_motor_bridge

[env:uno]
platform      = atmelavr
board         = uno
framework     = arduino
upload_port   = COM5
monitor_port  = COM5
monitor_speed = 115200
lib_deps      =
    adafruit/Adafruit SSD1306@^2.5.7
    adafruit/Adafruit GFX Library@^1.11.5

